#include "mainwindow.h"
#include <QApplication>
#include <QDir>

int main(int argc, char *argv[])
{
    QDir::setCurrent("/bin/");
    QApplication a(argc, argv);
    a.setStyleSheet("QPushButton {"
                    "border: 1px solid #515962;"
                    "background-color: #ffffff;"
                    "min-width: 80px;"
                    "color: #515962;"
                    "}"
                    "QPushButton:pressed {"
                    "background-color: #e5e5e5;"
                    "}"
                    "QPushButton:hover {"
                    "border: 2px solid #515962;"
                    "}"
                    "QLineEdit {"
                    "border: 1px solid #515962;"
                    "background-color: #ffffff;"
                    "color: #515962;"
                    "}"
                    "QLineEdit:hover {"
                    "border: 2px solid #515962;"
                    "}"
                    "QListView {"
                    "border: 1px solid #515962;"
                    "background-color: #ffffff;"
                    "color: #515962;"
                    "}"
                    "QListView::item:selected {"
                    "background-color: #e5e5e5;"
                    "}"
                    "QScrollBar:vertical {"
                    "border: 1px solid #515962;"
                    "background-color: #ffffff;"
                    "width: 15px;"
                    "}"
                    "QScrollBar::handle:vertical {"
                    "background-color: #c9c9c9;"
                    "min-height: 20px;"
                    "}"
                    "QScrollBar::add-line:vertical {"
                    "border: 1px solid #515962;"
                    "background-color: #ffffff;"
                    "height: 15px;"
                    "subcontrol-position: bottom;"
                    "subcontrol-origin: margin;"
                    "}"
                    "QScrollBar::sub-line:vertical {"
                    "border: 1px solid #515962;"
                    "background-color: #ffffff;"
                    "height: 15px;"
                    "subcontrol-position: top;"
                    "subcontrol-origin: margin;"
                    "}"
                    "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {"
                    "border: 1px solid #515962;"
                    "width: 3px;"
                    "height: 3px;"
                    "background: white;"
                    "}"
                    "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {"
                    "background: none;"
                    "}"
                    "QLabel {"
                    "color: #515962;"
                    "}"
                    "QMenu {"
                    "border: 1px solid #515962;"
                    "background-color: #ffffff;"
                    "color: #515962;"
                    "}"
                    "QMenu::item:selected {"
                    "background-color: #e5e5e5;"
                    "}"
                    "QMenuBar {"
                    "background-color: #ffffff;"
                    "}"
                    "QMenuBar::item {"
                    "background-color: #ffffff;"
                    "color: #515962;"
                    "}"
                    "QMenuBar::item:selected {"
                    "background-color: #e5e5e5;"
                    "}"
                    "QCheckBox {"
                    "color: #515962;"
                    "}"
                    "QRadioButton {"
                    "color: #515962;"
                    "}"
                    "QTabWidget::tab-bar {"
                    "background-color: #ffffff;"
                    "}"
                    "QTabBar::tab {"
                    "background-color: #ffffff;"
                    "color: #515962;"
                    "}"
                    "QTabBar::tab:selected {"
                    "background-color: #e5e5e5;"
                    "}");


    MainWindow w;
    w.show();

    return a.exec();
}
